workflows:
  web-workflow:
    name: Web Build
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build Web
        script: flutter build web --release
    artifacts:
      - build/web/**

  android-workflow:
    name: Android Build
    max_build_duration: 30
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
